source "https://rubygems.org/"
    
gem "json"
gem "json_pure"
gem "colorator"
gem "ffi"
gem "jekyll" 
gem "jekyll-feed"
gem "jekyll-gist"
gem "jekyll-paginate"
gem "jekyll-sass-converter"
gem "jekyll-watch" 
gem "jemoji"
gem "kramdown" 
gem "liquid" 
gem "mercenary" 
gem "rouge" 
gem "safe_yaml" 
gem "sass" 
gem "jekyll-sitemap" 
gem "listen" 
gem "rb-fsevent" 
gem "rb-inotify"

